spring.application.name=event-registration-platform

spring.datasource.url=jdbc:mysql://localhost:3306/event_registration_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kj2411880@gmail.com
spring.mail.password=havgmcugsnvtuplb
spring.mail.properties.mail.smtp.auth= true
spring.mail.properties.mail.smtp.starttls.enable=true


jwt.secret=ThisIsASecretKeyForJWTGenerationMakeItLongAndRandom123456
jwt.expiration=86400000


